-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-04-27 17:13:04 CEST
--   site:      SQL Server 2008
--   type:      SQL Server 2008


CREATE
  TABLE Uzytkownik
  (
    id_uzytkownik NUMERIC (11) NOT NULL IDENTITY NOT FOR REPLICATION ,
    u_nick        VARCHAR (15) NOT NULL ,
    u_password    VARCHAR (16) NOT NULL ,
    u_admin VARCHAR (1) NOT NULL DEFAULT 0 ,
    u_e_mail VARCHAR (100) NOT NULL ,
    u_blokada VARCHAR (1) NOT NULL DEFAULT 0
  )
  ON "default"
GO
ALTER TABLE Uzytkownik ADD CONSTRAINT Uzytkownik_PK PRIMARY KEY CLUSTERED (
id_uzytkownik)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO
ALTER TABLE Uzytkownik ADD CONSTRAINT Uzytkownik__UN UNIQUE NONCLUSTERED (
u_e_mail, u_nick)
ON "default"
GO

CREATE
  TABLE Posty
  (
    id_posty                 NUMERIC (11) NOT NULL IDENTITY NOT FOR REPLICATION ,
    p_link                   VARCHAR (200) NOT NULL ,
    p_data                   DATETIME NOT NULL ,
    Uzytkownik_id_uzytkownik NUMERIC (11) NOT NULL ,
    p_usun VARCHAR (1) NOT NULL DEFAULT 0 
  )
  ON "default"
GO
ALTER TABLE Posty ADD CONSTRAINT Posty_PK PRIMARY KEY CLUSTERED (id_posty)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Komentarze
  (
    id_komentarze            NUMERIC (11) NOT NULL IDENTITY NOT FOR REPLICATION ,
    k_note                   VARCHAR (500) NOT NULL ,
    k_data                   DATETIME NOT NULL ,
    Uzytkownik_id_uzytkownik NUMERIC (11) NOT NULL ,
    Posty_id_posty           NUMERIC (11) NOT NULL ,
    k_usun VARCHAR (1) DEFAULT 0
  )
  ON "default"
GO
ALTER TABLE Komentarze ADD CONSTRAINT Komentarze_PK PRIMARY KEY CLUSTERED (
id_komentarze)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO



ALTER TABLE Komentarze
ADD CONSTRAINT Komentarze_Posty_FK FOREIGN KEY
(
Posty_id_posty
)
REFERENCES Posty
(
id_posty
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Komentarze
ADD CONSTRAINT Komentarze_Uzytkownik_FK FOREIGN KEY
(
Uzytkownik_id_uzytkownik
)
REFERENCES Uzytkownik
(
id_uzytkownik
)
ON
DELETE
  CASCADE ON
UPDATE NO ACTION
GO

ALTER TABLE Posty
ADD CONSTRAINT Posty_Uzytkownik_FK FOREIGN KEY
(
Uzytkownik_id_uzytkownik
)
REFERENCES Uzytkownik
(
id_uzytkownik
)
ON
DELETE
  CASCADE ON
UPDATE NO ACTION
GO

ALTER TABLE Posty ADD CONSTRAINT DF_Posty DEFAULT GETDATE() FOR p_data
GO
ALTER TABLE Komentarze ADD CONSTRAINT DF_Komentarze DEFAULT GETDATE() FOR k_data
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


INSERT INTO Uzytkownik (u_nick,u_password,u_e_mail,u_admin)
VALUES ('Estagee','Estagee','estagee@gmail.com','1');
INSERT INTO Uzytkownik (u_nick,u_password,u_e_mail)
VALUES ('Hoggie','hoggie','hoggie@onet.pl');
INSERT INTO Uzytkownik (u_nick,u_password,u_e_mail)
VALUES ('Test','Test','test@o2.pl');

INSERT INTO posty 
(p_link,UZYTKOWNIK_ID_UZYTKOWNIK) VALUES('http://xd.cdn02.imgwykop.pl/c3397993/link_dBm8NJfqBdht1Jufynue2ItX9iS2cJGB,w300h223.jpg',1);

INSERT INTO posty 
(p_link,UZYTKOWNIK_ID_UZYTKOWNIK) VALUES('http://img2.cda.pl/g/154217_72682649944908910622.jpg',3);

INSERT INTO posty 
(p_link,UZYTKOWNIK_ID_UZYTKOWNIK) VALUES('https://cdn2.vox-cdn.com/thumbor/FNBQNNotpsvFLWnNsJAEjaLfyUo=/cdn0.vox-cdn.com/uploads/chorus_asset/file/3447312/madonnafall.0.gif',2);

INSERT INTO komentarze 
(k_note,UZYTKOWNIK_ID_UZYTKOWNIK,POSTY_ID_POSTY) VALUES('FINISZ HIMMM',2,3);

INSERT INTO komentarze
 (k_note,UZYTKOWNIK_ID_UZYTKOWNIK,POSTY_ID_POSTY) VALUES('Haha',3,1);
INSERT INTO komentarze 
 (k_note,UZYTKOWNIK_ID_UZYTKOWNIK,POSTY_ID_POSTY) VALUES('Ale gleba!!!',1,3);

